# Generated by Django 5.2.6 on 2025-10-16 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savingsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribution',
            name='amount',
            field=models.IntegerField(verbose_name='Amount Contributed (UGX)'),
        ),
    ]
